In [81]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/Users/emersonfrost/Desktop/caml_s2_7timesteps.csv')

In [3]:
df.head(5)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,ndti,ndvi,ndwi,red,red_edge,sample_date,satellite_date,.geo
0,494_20211017T145709_20211017T145703_T06CWP,0.873407,0.121020,0.907315,1.0,13.119000,0.912003,-97.779360,37.746683,-0.065962,0.012980,-0.008595,0.021573,0.888659,0.778616,2021-10-18,2021-10-17,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,494_20211016T152649_20211016T152648_T06CWP,0.882117,0.101252,0.867247,-1.0,13.119000,0.874108,-97.779360,37.746683,-0.041234,0.011887,0.016480,-0.004595,0.853579,0.785921,2021-10-18,2021-10-16,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,495_20211017T145709_20211017T145703_T06CWP,0.869185,0.133041,0.903888,1.0,51.294998,0.907735,-97.531050,37.782400,-0.066456,0.012869,-0.008817,0.021683,0.884664,0.774405,2021-10-18,2021-10-17,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,654_20191006T155329_20191006T155327_T07CDL,0.820199,0.165632,0.845527,-1.0,8.505000,0.735485,-99.431327,39.415903,-0.019956,-0.038918,0.015663,-0.054545,0.795111,0.763826,2019-10-07,2019-10-06,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,654_20191006T155329_20191006T155327_T07CEL,0.821885,0.166132,0.803108,-1.0,8.505000,0.697557,-99.431327,39.415903,0.007119,-0.039571,0.042451,-0.081883,0.755092,0.765796,2019-10-07,2019-10-06,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [7]:
df = df[(df['cyanobacteria_abundance'] < 155) & (df['cyanobacteria_abundance'] > 154)]

In [8]:
df

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,ndti,ndvi,ndwi,red,red_edge,sample_date,satellite_date,.geo
16,772_20191027T051719_20191027T051716_T37CER,0.886035,0.147999,0.938286,1.0,154.600006,0.927308,-75.886498,41.332803,-0.032811,0.016988,-0.005775,0.022761,0.896329,0.839383,2019-10-30,2019-10-27,"{""type"":""MultiPoint"",""coordinates"":[]}"
17,772_20191017T051719_20191017T051716_T37CER,0.809199,0.173370,0.862755,1.0,154.600006,0.849353,-75.886498,41.332803,-0.034522,0.017728,-0.006482,0.024207,0.819760,0.765052,2019-10-30,2019-10-17,"{""type"":""MultiPoint"",""coordinates"":[]}"
18,772_20191017T051719_20191017T051716_T38CMA,0.808937,0.173429,0.861800,1.0,154.600006,0.848851,-75.886498,41.332803,-0.034158,0.017818,-0.006258,0.024074,0.819128,0.765019,2019-10-30,2019-10-17,"{""type"":""MultiPoint"",""coordinates"":[]}"
19,772_20191003T053709_20191003T053712_T37CER,0.881250,0.158770,0.906127,-1.0,154.600006,0.884912,-75.886498,41.332803,-0.033871,0.003094,0.001067,0.002028,0.879463,0.821779,2019-10-30,2019-10-03,"{""type"":""MultiPoint"",""coordinates"":[]}"
20,772_20190927T051719_20190927T051932_T37CER,0.684532,0.159232,0.754538,1.0,154.600006,0.705848,-75.886498,41.332803,-0.030803,0.015720,0.000393,0.015328,0.684009,0.643130,2019-10-30,2019-09-27,"{""type"":""MultiPoint"",""coordinates"":[]}"
21,772_20190927T051719_20190927T051932_T38CMA,0.684521,0.159276,0.753948,1.0,154.600006,0.705782,-75.886498,41.332803,-0.030230,0.016135,0.000845,0.015290,0.683377,0.643274,2019-10-30,2019-09-27,"{""type"":""MultiPoint"",""coordinates"":[]}"
22,772_20190923T053709_20190923T053718_T37CER,0.862452,0.180003,0.888042,1.0,154.600006,0.838427,-75.886498,41.332803,-0.009256,-0.002806,0.011324,-0.014130,0.843161,0.827667,2019-10-30,2019-09-23,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [9]:
df2 = pd.read_csv('/Users/emersonfrost/Desktop/caml_90days_previous.csv')

In [10]:
df2.shape

(194235, 18)

In [12]:
df.shape

(7, 18)

In [13]:
df2.head(5)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,ndti,ndvi,ndwi,red,red_edge,sample_date,satellite_date,.geo
0,0_20200404T170851_20200404T171737_T14SQJ,0.303042,0.338892,0.276812,0.784902,6.061,0.278933,39.141931,-95.479569,0.061518,-0.005008,0.036407,-0.041403,0.281921,0.318489,2020-06-29,2020-04-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,0_20200404T170851_20200404T171737_T15STD,0.301742,0.338304,0.274842,0.723308,6.061,0.277107,39.141931,-95.479569,0.063106,-0.005193,0.037172,-0.042355,0.280170,0.317642,2020-06-29,2020-04-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,0_20200409T170849_20200409T172046_T14SQJ,0.190471,0.242455,0.179102,0.559030,6.061,0.186306,39.141931,-95.479569,0.114497,0.040531,0.049144,-0.008665,0.173056,0.216059,2020-06-29,2020-04-09,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,0_20200409T170849_20200409T172046_T15STD,0.189511,0.241976,0.178344,0.545731,6.061,0.185647,39.141931,-95.479569,0.114474,0.040177,0.047975,-0.007842,0.172519,0.215444,2020-06-29,2020-04-09,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,0_20200414T170851_20200414T171907_T14SQJ,0.079389,0.095053,0.046439,0.150185,6.061,0.066794,39.141931,-95.479569,-0.114757,0.001956,0.051338,-0.049359,0.071396,0.069393,2020-06-29,2020-04-14,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [14]:
df2.cyanobacteria_abundance.nunique()

6327

In [16]:
df2.columns

Index(['system:index', 'NIR', 'SWIR', 'blue', 'cloud_score',
       'cyanobacteria_abundance', 'green', 'latitude', 'longitude', 'ndci',
       'ndti', 'ndvi', 'ndwi', 'red', 'red_edge', 'sample_date',
       'satellite_date', '.geo'],
      dtype='object')

In [22]:
a = df2['cyanobacteria_abundance'].iloc[0]
print(a)
temp_df = df2[df2['cyanobacteria_abundance'] == a]

6.060999870300293

In [23]:
temp_df.shape

(36, 18)

In [25]:
temp_df.head(36)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,ndti,ndvi,ndwi,red,red_edge,sample_date,satellite_date,.geo
0,0_20200404T170851_20200404T171737_T14SQJ,0.303042,0.338892,0.276812,0.784902,6.061,0.278933,39.141931,-95.479569,0.061518,-0.005008,0.036407,-0.041403,0.281921,0.318489,2020-06-29,2020-04-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
1,0_20200404T170851_20200404T171737_T15STD,0.301742,0.338304,0.274842,0.723308,6.061,0.277107,39.141931,-95.479569,0.063106,-0.005193,0.037172,-0.042355,0.280170,0.317642,2020-06-29,2020-04-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
2,0_20200409T170849_20200409T172046_T14SQJ,0.190471,0.242455,0.179102,0.559030,6.061,0.186306,39.141931,-95.479569,0.114497,0.040531,0.049144,-0.008665,0.173056,0.216059,2020-06-29,2020-04-09,"{""type"":""MultiPoint"",""coordinates"":[]}"
3,0_20200409T170849_20200409T172046_T15STD,0.189511,0.241976,0.178344,0.545731,6.061,0.185647,39.141931,-95.479569,0.114474,0.040177,0.047975,-0.007842,0.172519,0.215444,2020-06-29,2020-04-09,"{""type"":""MultiPoint"",""coordinates"":[]}"
4,0_20200414T170851_20200414T171907_T14SQJ,0.079389,0.095053,0.046439,0.150185,6.061,0.066794,39.141931,-95.479569,-0.114757,0.001956,0.051338,-0.049359,0.071396,0.069393,2020-06-29,2020-04-14,"{""type"":""MultiPoint"",""coordinates"":[]}"
5,0_20200414T170851_20200414T171907_T15STD,0.080628,0.095350,0.046922,0.137024,6.061,0.067201,39.141931,-95.479569,-0.093330,0.002507,0.059828,-0.057855,0.071690,0.071162,2020-06-29,2020-04-14,"{""type"":""MultiPoint"",""coordinates"":[]}"
6,0_20200419T170849_20200419T171657_T14SQJ,0.131036,0.112680,0.115973,0.407196,6.061,0.127153,39.141931,-95.479569,0.018131,0.020699,0.030652,-0.009954,0.122837,0.128532,2020-06-29,2020-04-19,"{""type"":""MultiPoint"",""coordinates"":[]}"
7,0_20200419T170849_20200419T171657_T15STD,0.131934,0.113129,0.117055,0.446390,6.061,0.127851,39.141931,-95.479569,0.017487,0.021611,0.032572,-0.010969,0.123273,0.128820,2020-06-29,2020-04-19,"{""type"":""MultiPoint"",""coordinates"":[]}"
8,0_20200424T170851_20200424T171631_T14SQJ,1.065424,0.231537,1.016762,1.000000,6.061,1.041973,39.141931,-95.479569,-0.018196,-0.009367,0.001761,-0.011128,1.061678,1.023734,2020-06-29,2020-04-24,"{""type"":""MultiPoint"",""coordinates"":[]}"
9,0_20200424T170851_20200424T171631_T15STD,1.065165,0.231340,1.018101,1.000000,6.061,1.042584,39.141931,-95.479569,-0.018799,-0.009305,0.001409,-0.010714,1.062169,1.022972,2020-06-29,2020-04-24,"{""type"":""MultiPoint"",""coordinates"":[]}"
10,0_20200429T170849_20200429T171636_T14SQJ,0.014577,0.010736,0.028806,0.399316,6.061,0.026752,39.141931,-95.479569,-0.766205,0.170500,-0.151868,0.310888,0.019191,0.003699,2020-06-29,2020-04-29,"{""type"":""MultiPoint"",""coordinates"":[]}"
11,0_20200429T170849_20200429T171636_T15STD,0.014252,0.010616,0.028561,0.414990,6.061,0.026384,39.141931,-95.479569,-0.782186,0.172414,-0.154273,0.314893,0.018873,0.003587,2020-06-29,2020-04-29,"{""type"":""MultiPoint"",""coordinates"":[]}"
12,0_20200504T170901_20200504T171658_T14SQJ,1.348811,0.275551,1.320333,0.999206,6.061,1.260044,39.141931,-95.479569,-0.035196,0.020793,0.054780,-0.034026,1.208715,1.126516,2020-06-29,2020-05-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
13,0_20200504T170901_20200504T171658_T15STD,1.072350,0.265412,1.034135,1.000000,6.061,1.061412,39.141931,-95.479569,-0.009942,-0.003865,0.001262,-0.005127,1.069651,1.048585,2020-06-29,2020-05-04,"{""type"":""MultiPoint"",""coordinates"":[]}"
14,0_20200509T170849_20200509T171606_T14SQJ,0.923761,0.211342,1.094628,0.817406,6.061,0.978612,39.141931,-95.479569,-0.044065,0.041603,0.012787,0.028831,0.900439,0.824428,2020-06-29,2020-05-09,"{""type"":""MultiPoint"",""coordinates"":[]}"
15,0_20200509T170849_20200509T171606_T15STD,0.928660,0.211549,1.095057,0.834360,6.061,0.979707,39.141931,-95.479569,-0.042474,0.042176,0.015445,0.026748,0.900413,0.827037,2020-06-29,2020-05-09,"{""type"":""MultiPoint"",""coordinates"":[]}"
16,0_20200514T170901_20200514T171659_T14SQJ,0.156138,0.227836,0.079960,0.432534,6.061,0.113361,39.141931,-95.479569,0.092161,-0.090495,0.070240,-0.159502,0.137089,0.168240,2020-06-29,2020-05-14,"{""type"":""MultiPoint"",""coordinates"":[]}"
17,0_20200514T170901_20200514T171659_T15STD,0.157145,0.228423,0.080561,0.386784,6.061,0.113812,39.141931,-95.479569,0.091938,-0.090178,0.072320,-0.160863,0.137551,0.169353,2020-06-29,2020-05-14,"{""type"":""MultiPoint"",""coordinates"":[]}"
18,0_20200519T170849_20200519T171832_T14SQJ,0.700258,0.615821,0.723582,0.893098,6.061,0.686260,39.141931,-95.479569,0.015002,0.014300,0.024399,-0.010103,0.666910,0.687232,2020-06-29,2020-05-19,"{""type"":""MultiPoint"",""coordinates"":[]}"
19,0_20200519T170849_20200519T171832_T15STD,0.701026,0.616174,0.723793,0.929931,6.061,0.686612,39.141931,-95.479569,0.015032,0.014420,0.024807,-0.010391,0.667090,0.687458,2020-06-29,2020-05-19,"{""type"":""MultiPoint"",""coordinates"":[]}"
20,0_20200524T170901_20200524T171432_T14SQJ,0.190035,0.253886,0.100443,0.943237,6.061,0.142707,39.141931,-95.479569,0.130580,-0.080909,0.062250,-0.142485,0.169230,0.220896,2020-06-29,2020-05-24,"{""type"":""MultiPoint"",""coordinates"":[]}"
21,0_20200524T170901_20200524T171432_T15STD,0.189153,0.251826,0.101135,0.880896,6.061,0.143140,39.141931,-95.479569,0.124508,-0.079320,0.058457,-0.136949,0.169229,0.220230,2020-06-29,2020-05-24,"{""type"":""MultiPoint"",""coordinates"":[]}"
22,0_20200529T170849_20200529T171931_T14SQJ,0.091094,0.105044,0.050018,0.018977,6.061,0.074935,39.141931,-95.479569,-0.030049,0.002435,0.061381,-0.058904,0.079555,0.089163,2020-06-29,2020-05-29,"{""type"":""MultiPoint"",""coordinates"":[]}"
23,0_20200529T170849_20200529T171931_T15STD,0.087770,0.096198,0.049375,0.001866,6.061,0.073018,39.141931,-95.479569,-0.032230,0.010519,0.069810,-0.059611,0.076403,0.082981,2020-06-29,2020-05-29,"{""type"":""MultiPoint"",""coordinates"":[]}"
24,0_20200603T170901_20200603T172247_T14SQJ,0.081282,0.084483,0.047696,0.219006,6.061,0.069243,39.141931,-95.479569,-0.016626,0.031981,0.072442,-0.041248,0.068386,0.081324,2020-06-29,2020-06-03,"{""type"":""MultiPoint"",""coordinates"":[]}"
25,0_20200603T170901_20200603T172247_T15STD,0.082030,0.084712,0.047953,0.114175,6.061,0.069441,39.141931,-95.479569,-0.004716,0.030970,0.079951,-0.049882,0.068749,0.082511,2020-06-29,2020-06-03,"{""type"":""MultiPoint"",""coordinates"":[]}"
26,0_20200608T170849_20200608T171643_T14SQJ,0.143185,0.123697,0.105912,0.507402,6.061,0.133049,39.141931,-95.479569,0.032083,0.026482,0.060363,-0.033887,0.126857,0.141106,2020-06-29,2020-06-08,"{""type"":""MultiPoint"",""coordinates"":[]}"
27,0_20200608T170849_20200608T171643_T15STD,0.143878,0.124418,0.105933,0.530417,6.061,0.133313,39.141931,-95.479569,0.035417,0.026727,0.062074,-0.035366,0.127093,0.142066,2020-06-29,2020-06-08,"{""type"":""MultiPoint"",""coordinates"":[]}"
28,0_20200613T170901_20200613T171740_T14SQJ,0.155281,0.140508,0.100934,0.000144,6.061,0.134281,39.141931,-95.479569,0.033782,0.001446,0.070001,-0.068457,0.135741,0.151490,2020-06-29,2020-06-13,"{""type"":""MultiPoint"",""coordinates"":[]}"
29,0_20200613T170901_20200613T171740_T15STD,0.156353,0.141339,0.101265,0.016377,6.061,0.134941,39.141931,-95.479569,0.032945,0.000799,0.070182,-0.069289,0.136577,0.152031,2020-06-29,2020-06-13,"{""type"":""MultiPoint"",""coordinates"":[]}"
30,0_20200618T170849_20200618T171954_T14SQJ,0.187319,0.248366,0.100435,0.741976,6.061,0.142950,39.141931,-95.479569,0.061782,-0.064427,0.069527,-0.132970,0.164510,0.195042,2020-06-29,2020-06-18,"{""type"":""MultiPoint"",""coordinates"":[]}"
31,0_20200618T170849_20200618T171954_T15STD,0.182430,0.245532,0.100586,0.599386,6.061,0.139535,39.141931,-95.479569,0.087799,-0.059062,0.073079,-0.131211,0.158843,0.197415,2020-06-29,2020-06-18,"{""type"":""MultiPoint"",""coordinates"":[]}"
32,0_20200623T170901_20200623T171555_T14SQJ,0.182890,0.267029,0.086443,0.011591,6.061,0.130401,39.141931,-95.479569,0.112418,-0.097129,0.072832,-0.168796,0.159899,0.202693,2020-06-29,2020-06-23,"{""type"":""MultiPoint"",""coordinates"":[]}"
33,0_20200623T170901_20200623T171555_T15STD,0.181488,0.265328,0.087145,0.009187,6.061,0.130896,39.141931,-95.479569,0.109690,-0.094321,0.068596,-0.161728,0.159696,0.203178,2020-06-29,2020-06-23,"{""type"":""MultiPoint"",""coordinates"":[]}"
34,0_20200628T170849_20200628T171856_T14SQJ,0.182998,0.237191,0.098929,0.206514,6.061,0.138732,39.141931,-95.479569,0.123506,-0.063724,0.076877,-0.139926,0.158113,0.205998,2020-06-29,2020-06-28,"{""type"":""MultiPoint"",""coordinates"":[]}"
35,0_20200628T170849_20200628T171856_T15STD,0.181321,0.235477,0.099244,0.171287,6.061,0.138139,39.141931,-95.479569,0.126762,-0.061338,0.076608,-0.137279,0.156731,0.206391,2020-06-29,2020-06-28,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [ ]:
#removing duplicates
#limiting the the most recent 9 per point
#calculate some sort of difference days metric (avg. separation, total diff_days)
#prompt google earth engine for the 40 days after (get the next 5)
#normalized cloud score / look into this...

In [54]:
#dropping default values... 
to_drop = df2[df2['NIR'] == -999]
to_drop.shape
print(df2.shape)
df2 = df2[(df2['green'] != -999) & (df2['blue'] != -999) & (df2['SWIR'] != -999) & (df2['NIR'] != -999)]
print(df2.shape)

(193945, 18)
(193945, 18)
Under 20%:  (80223, 18)

In [55]:
#set a cloud coverage limit (drop anything with cloud coverage over a chosen barrier)
#create multiple datasets with different cloud coverages 
#20% 
df_under20 = df2[df2['cloud_score'] <= 0.2]
print("Under 20%: ", df_under20.shape)
#30%
df_under30 = df2[df2['cloud_score'] <= 0.3]
print("Under 30%: ", df_under30.shape)
#50% 
df_under50 = df2[df2['cloud_score'] <= 0.5]
print("Under 50%: ", df_under50.shape)
#70%
df_under70 = df2[df2['cloud_score'] <= 0.7]
print("Under 70%: ", df_under70.shape)

Under 20%:  (80223, 18)
Under 30%:  (92712, 18)
Under 50%:  (115156, 18)
Under 70%:  (133298, 18)

In [82]:
#percentages
print(df_under20.shape[0] / df2.shape[0])
print(df_under30.shape[0] / df2.shape[0])
print(df_under50.shape[0] / df2.shape[0])
print(df_under70.shape[0] / df2.shape[0])

0.41363788702982807
0.4780324318750161
0.593755961741731
0.6872979452937689

In [57]:
#removing duplicates ... keep the version that has a lower cloud score
df_under20_clean = (df_under20.sort_values('cloud_score', ascending = True).drop_duplicates(subset = ['cyanobacteria_abundance','sample_date', 'satellite_date']))
df_under30_clean = (df_under30.sort_values('cloud_score', ascending = True).drop_duplicates(subset = ['cyanobacteria_abundance','sample_date', 'satellite_date']))
df_under50_clean = (df_under50.sort_values('cloud_score', ascending = True).drop_duplicates(subset = ['cyanobacteria_abundance','sample_date', 'satellite_date']))
df_under70_clean = (df_under70.sort_values('cloud_score', ascending = True).drop_duplicates(subset = ['cyanobacteria_abundance','sample_date', 'satellite_date']))

In [71]:
print(df_under20_clean.shape)
print(df_under30_clean.shape)
print(df_under50_clean.shape)
print(df_under70_clean.shape)

(65798, 18)
(75522, 18)
(92792, 18)
(106343, 18)

In [72]:
print(df_under20_clean.cyanobacteria_abundance.nunique())
print(df_under20_clean.cyanobacteria_abundance.nunique() * 9)

print(df_under30_clean.cyanobacteria_abundance.nunique())
print(df_under30_clean.cyanobacteria_abundance.nunique() * 9)

print(df_under50_clean.cyanobacteria_abundance.nunique())
print(df_under50_clean.cyanobacteria_abundance.nunique() * 9)

print(df_under70_clean.cyanobacteria_abundance.nunique())
print(df_under70_clean.cyanobacteria_abundance.nunique() * 9)

6202
55818
6237
56133
6290
56610
6299
56691

In [73]:
df_under20_recent9 = (
    df_under20_clean.sort_values('satellite_date', ascending=False)
      .groupby(['cyanobacteria_abundance', 'sample_date'])
      .head(9)
)

In [74]:
df_under20_recent9.shape

(47822, 18)

In [78]:
df_under20_recent9.sort_values('cyanobacteria_abundance', ascending = False).head(10)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,ndti,ndvi,ndwi,red,red_edge,sample_date,satellite_date,.geo
136904,6549_20190820T174911_20190820T175236_T13TCH,0.263234,0.365387,0.158199,0.139056,154213.8796,0.197932,42.500722,-106.910185,0.173069,-0.077583,0.067998,-0.144550,0.230379,0.326173,2019-08-27,2019-08-20,"{""type"":""MultiPoint"",""coordinates"":[]}"
136898,6549_20190805T174919_20190805T180037_T13TCH,0.214024,0.306174,0.123232,0.003340,154213.8796,0.156594,42.500722,-106.910185,0.155439,-0.067256,0.082871,-0.148795,0.181192,0.254585,2019-08-27,2019-08-05,"{""type"":""MultiPoint"",""coordinates"":[]}"
136900,6549_20190810T174911_20190810T180109_T13TCH,0.233127,0.328170,0.131847,0.054680,154213.8796,0.169364,42.500722,-106.910185,0.179154,-0.074342,0.083519,-0.156558,0.196569,0.287066,2019-08-27,2019-08-10,"{""type"":""MultiPoint"",""coordinates"":[]}"
136906,6549_20190825T174909_20190825T180034_T13TCH,0.251123,0.384191,0.144589,0.010715,154213.8796,0.183027,42.500722,-106.910185,0.192101,-0.083278,0.078578,-0.160549,0.215344,0.316317,2019-08-27,2019-08-25,"{""type"":""MultiPoint"",""coordinates"":[]}"
136903,6549_20190818T175919_20190818T180749_T13TCH,0.235783,0.351672,0.137194,0.000008,154213.8796,0.174707,42.500722,-106.910185,0.184585,-0.081931,0.071238,-0.151946,0.204745,0.297199,2019-08-27,2019-08-18,"{""type"":""MultiPoint"",""coordinates"":[]}"
136897,6549_20190803T175921_20190803T180658_T13TCH,0.222653,0.262374,0.156659,0.060581,154213.8796,0.182934,42.500722,-106.910185,0.119321,-0.039362,0.057716,-0.096824,0.198217,0.253579,2019-08-27,2019-08-03,"{""type"":""MultiPoint"",""coordinates"":[]}"
136896,6549_20190731T174911_20190731T175632_T13TCH,0.260224,0.265253,0.192416,0.013879,154213.8796,0.214855,42.500722,-106.910185,0.111155,-0.032562,0.062472,-0.094820,0.229567,0.287737,2019-08-27,2019-07-31,"{""type"":""MultiPoint"",""coordinates"":[]}"
136901,6549_20190813T175921_20190813T180013_T13TCH,0.218514,0.309514,0.122943,0.031558,154213.8796,0.158726,42.500722,-106.910185,0.183243,-0.080575,0.078640,-0.157844,0.186353,0.273522,2019-08-27,2019-08-13,"{""type"":""MultiPoint"",""coordinates"":[]}"
136902,6549_20190815T174919_20190815T175713_T13TCH,0.241553,0.358398,0.138719,0.072558,154213.8796,0.175156,42.500722,-106.910185,0.186215,-0.080464,0.080584,-0.159791,0.205387,0.300749,2019-08-27,2019-08-15,"{""type"":""MultiPoint"",""coordinates"":[]}"
111604,5331_20210617T155901_20210617T160630_T17TPE,0.118173,0.184344,0.058710,0.056339,120193.3330,0.087992,40.113770,-79.527809,0.499234,0.113176,0.234218,-0.129573,0.072757,0.270704,2021-08-30,2021-06-17,"{""type"":""MultiPoint"",""coordinates"":[]}"

In [83]:
#display number of unique samples + the number of samples w/ n previous...
#ie how many with 9, 8, 7 --> used to determine final sample size + shape of input
a_list = [df_under20_clean, df_under30_clean, df_under50_clean, df_under70_clean]
for temp in a_list:
    counts = (
        temp.groupby(['sample_date', 'latitude', 'longitude', 'cyanobacteria_abundance'])
          .size()
          .reset_index(name='n_obs')
    )

    n_7 = (counts['n_obs'] >= 7).sum()
    n_8 = (counts['n_obs'] >= 8).sum()
    n_9 = (counts['n_obs'] >= 9).sum()

    print(n_7, n_8, n_9)

    print(n_7 / 6327 , n_8 / 6327 , n_9 / 6327)

4088 3493 3053
0.6461198040145408 0.5520783941836573 0.4825351667456931
4790 4237 3754
0.7570728623360202 0.6696696696696697 0.5933301722775407
5889 5403 4863
0.9307728781412992 0.853959222380275 0.768610715979137
6320 5973 5619
0.9988936304725778 0.944049312470365 0.8880986249407302

In [87]:
#returning 3 possible training data frames for the forecaster

#1 - 7 time points before w/ a cloud coverage limit @ 0.3
df_one = (
    df_under30_clean.sort_values('satellite_date', ascending=False)
      .groupby(['cyanobacteria_abundance', 'sample_date'])
        .filter(lambda x: len(x) >= 7)
        .groupby(['cyanobacteria_abundance', 'sample_date'])
        .head(7)
)

#2 - 9 time points w/ a cloud coverage limit @ 0.7
df_two = (
    df_under70_clean.sort_values('satellite_date', ascending=False)
      .groupby(['cyanobacteria_abundance', 'sample_date'])
        .filter(lambda x: len(x) >= 9)
        .groupby(['cyanobacteria_abundance', 'sample_date'])
        .head(9)
)
#3 - 8 time points w/ a cloud coverage limit @ 0.5
df_three = (
    df_under50_clean.sort_values('satellite_date', ascending=False)
      .groupby(['cyanobacteria_abundance', 'sample_date'])
        .filter(lambda x: len(x) >= 8)
        .groupby(['cyanobacteria_abundance', 'sample_date'])
        .head(8)
)

print(df_one.shape)
print(df_two.shape)
print(df_three.shape)
print(df_one.shape[0] / 7)
print(df_two.shape[0] / 9)
print(df_three.shape[0] / 8)

(33628, 18)
(50760, 18)
(43424, 18)
4804.0
5640.0
5428.0

In [94]:
#now calculated columns
#put in datetime
df_one['sample_date'] = pd.to_datetime(df_one['sample_date'])
df_one['satellite_date'] = pd.to_datetime(df_one['satellite_date'])
#sorting
df_one = df_one.sort_values(['sample_date', 'cyanobacteria_abundance'])

#calculating statistics
group_cols = ['sample_date', 'cyanobacteria_abundance']

def compute_time_features(group):
    group = group.sort_values('satellite_date')
    
    #create list of differences within each sample
    diffs = group['satellite_date'].diff().dt.days.dropna()
    
    #calculating the total difference
    tot_diff = (group['sample_date'].iloc[0] - group['satellite_date'].iloc[0]).days
    
    return pd.Series({
        'tot_diff_days': tot_diff,
        'mean_diff_days': diffs.mean(),
        'median_diff_days': diffs.median(),
        'std_diff_days': diffs.std()
    })

time_features_one = df_one.groupby(group_cols).apply(compute_time_features).reset_index()

print(time_features_one.shape)
time_features_one.head(5)

(4804, 6)

/var/folders/9z/ltjvr1610w9g431sszz26tr40000gn/T/ipykernel_5495/5248470.py:27: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  time_features_one = df_one.groupby(group_cols).apply(compute_time_features).reset_index()

,sample_date,cyanobacteria_abundance,tot_diff_days,mean_diff_days,median_diff_days,std_diff_days
0,2016-01-21,3824.500000,71.0,11.166667,10.0,5.269409
1,2016-01-21,5943.000000,71.0,11.166667,10.0,5.269409
2,2016-04-12,1201.413452,90.0,13.833333,10.0,8.010410
3,2016-04-12,1308.878052,90.0,13.833333,10.0,8.010410
4,2016-04-12,2201.158936,90.0,13.833333,10.0,8.010410

In [97]:
#now do the same for dfs 2 and 3
#dataframe 2
#put in datetime
df_two['sample_date'] = pd.to_datetime(df_two['sample_date'])
df_two['satellite_date'] = pd.to_datetime(df_two['satellite_date'])
#sorting
df_two = df_two.sort_values(['sample_date', 'cyanobacteria_abundance'])

time_features_two = df_two.groupby(group_cols).apply(compute_time_features).reset_index()

print(time_features_two.shape)
time_features_two.head(5)

#dataframe 3: 
#put in datetime
df_three['sample_date'] = pd.to_datetime(df_three['sample_date'])
df_three['satellite_date'] = pd.to_datetime(df_three['satellite_date'])
#sorting
df_three = df_three.sort_values(['sample_date', 'cyanobacteria_abundance'])

time_features_three = df_three.groupby(group_cols).apply(compute_time_features).reset_index()

print(time_features_three.shape)
time_features_three.head(5)

/var/folders/9z/ltjvr1610w9g431sszz26tr40000gn/T/ipykernel_5495/851668882.py:9: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  time_features_two = df_two.groupby(group_cols).apply(compute_time_features).reset_index()

(5640, 6)
(5428, 6)

/var/folders/9z/ltjvr1610w9g431sszz26tr40000gn/T/ipykernel_5495/851668882.py:21: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  time_features_three = df_three.groupby(group_cols).apply(compute_time_features).reset_index()

,sample_date,cyanobacteria_abundance,tot_diff_days,mean_diff_days,median_diff_days,std_diff_days
0,2016-01-21,3824.500000,71.0,10.000000,10.0,5.715476
1,2016-01-21,5943.000000,71.0,10.000000,10.0,5.715476
2,2016-03-07,571.125000,87.0,11.428571,10.0,5.798193
3,2016-04-12,1201.413452,77.0,10.000000,10.0,5.131601
4,2016-04-12,1308.878052,77.0,10.000000,10.0,5.131601

In [98]:
#now merge everything back to final dataframes
df_one_final = df_one.merge(time_features_one, on=group_cols)
print(df_one_final.shape)

df_two_final = df_two.merge(time_features_two, on = group_cols)
print(df_two_final.shape)

df_three_final = df_three.merge(time_features_three, on = group_cols)
print(df_three_final.shape)

(33628, 22)
(50760, 22)
(43424, 22)

In [99]:
df_one_final.head(5)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,...,ndwi,red,red_edge,sample_date,satellite_date,.geo,tot_diff_days,mean_diff_days,median_diff_days,std_diff_days
0,9062_20160117T182712_20160117T183427_T11SMT,0.117157,0.197307,0.068217,0.072852,3824.5,0.086842,33.4742,-117.137998,0.302050,...,-0.246461,0.101563,0.159807,2016-01-21,2016-01-17,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,11.166667,10.0,5.269409
1,9062_20151231T183752_20151231T183755_T11SMT,0.118239,0.181915,0.073154,0.000228,3824.5,0.094558,33.4742,-117.137998,0.270032,...,-0.209679,0.108157,0.153717,2016-01-21,2015-12-31,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,11.166667,10.0,5.269409
2,9062_20151228T183312_20151228T183309_T11SMT,0.138406,0.206684,0.087906,0.072584,3824.5,0.108789,33.4742,-117.137998,0.275410,...,-0.193040,0.119495,0.181531,2016-01-21,2015-12-28,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,11.166667,10.0,5.269409
3,9062_20151218T182802_20151218T182756_T11SMT,0.126158,0.202519,0.072346,0.000702,3824.5,0.094635,33.4742,-117.137998,0.345760,...,-0.253196,0.106488,0.180982,2016-01-21,2015-12-18,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,11.166667,10.0,5.269409
4,9062_20151208T183312_20151208T183309_T11SMT,0.129843,0.200796,0.070884,0.038293,3824.5,0.094722,33.4742,-117.137998,0.361775,...,-0.242766,0.105682,0.189615,2016-01-21,2015-12-08,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,11.166667,10.0,5.269409

In [100]:
df_two_final.head(5)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,...,ndwi,red,red_edge,sample_date,satellite_date,.geo,tot_diff_days,mean_diff_days,median_diff_days,std_diff_days
0,9062_20160120T184422_20160120T184423_T11SMT,0.045535,0.057598,0.039826,0.438961,3824.5,0.042429,33.4742,-117.137998,0.184636,...,-0.067770,0.042490,0.058524,2016-01-21,2016-01-20,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,8.75,8.5,5.87367
1,9062_20160117T182712_20160117T183427_T11SMT,0.117157,0.197307,0.068217,0.072852,3824.5,0.086842,33.4742,-117.137998,0.302050,...,-0.246461,0.101563,0.159807,2016-01-21,2016-01-17,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,8.75,8.5,5.87367
2,9062_20151231T183752_20151231T183755_T11SMT,0.118239,0.181915,0.073154,0.000228,3824.5,0.094558,33.4742,-117.137998,0.270032,...,-0.209679,0.108157,0.153717,2016-01-21,2015-12-31,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,8.75,8.5,5.87367
3,9062_20151228T183312_20151228T183309_T11SMT,0.138406,0.206684,0.087906,0.072584,3824.5,0.108789,33.4742,-117.137998,0.275410,...,-0.193040,0.119495,0.181531,2016-01-21,2015-12-28,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,8.75,8.5,5.87367
4,9062_20151221T184432_20151221T184427_T11SMT,0.126152,0.182527,0.070420,0.682572,3824.5,0.097656,33.4742,-117.137998,0.308431,...,-0.230901,0.110245,0.171470,2016-01-21,2015-12-21,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,8.75,8.5,5.87367

In [104]:
df_three_final.head(16)

,system:index,NIR,SWIR,blue,cloud_score,cyanobacteria_abundance,green,latitude,longitude,ndci,...,ndwi,red,red_edge,sample_date,satellite_date,.geo,tot_diff_days,mean_diff_days,median_diff_days,std_diff_days
0,9062_20160120T184422_20160120T184423_T11SMT,0.045535,0.057598,0.039826,0.438961,3824.5,0.042429,33.474200,-117.137998,0.184636,...,-0.067770,0.042490,0.058524,2016-01-21,2016-01-20,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
1,9062_20160117T182712_20160117T183427_T11SMT,0.117157,0.197307,0.068217,0.072852,3824.5,0.086842,33.474200,-117.137998,0.302050,...,-0.246461,0.101563,0.159807,2016-01-21,2016-01-17,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
2,9062_20151231T183752_20151231T183755_T11SMT,0.118239,0.181915,0.073154,0.000228,3824.5,0.094558,33.474200,-117.137998,0.270032,...,-0.209679,0.108157,0.153717,2016-01-21,2015-12-31,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
3,9062_20151228T183312_20151228T183309_T11SMT,0.138406,0.206684,0.087906,0.072584,3824.5,0.108789,33.474200,-117.137998,0.275410,...,-0.193040,0.119495,0.181531,2016-01-21,2015-12-28,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
4,9062_20151218T182802_20151218T182756_T11SMT,0.126158,0.202519,0.072346,0.000702,3824.5,0.094635,33.474200,-117.137998,0.345760,...,-0.253196,0.106488,0.180982,2016-01-21,2015-12-18,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
5,9062_20151208T183312_20151208T183309_T11SMT,0.129843,0.200796,0.070884,0.038293,3824.5,0.094722,33.474200,-117.137998,0.361775,...,-0.242766,0.105682,0.189615,2016-01-21,2015-12-08,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
6,9062_20151121T184422_20151121T184425_T11SMT,0.128463,0.192753,0.074177,0.000007,3824.5,0.098254,33.474200,-117.137998,0.374142,...,-0.241988,0.107506,0.188575,2016-01-21,2015-11-21,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
7,9062_20151111T184002_20151111T183956_T11SMT,0.122889,0.180506,0.078283,0.012064,3824.5,0.103311,33.474200,-117.137998,0.404530,...,-0.200453,0.106544,0.196478,2016-01-21,2015-11-11,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
8,9063_20160120T184422_20160120T184423_T11SMT,0.094421,0.208966,0.040405,0.438961,5943.0,0.055817,33.477901,-117.141998,0.388770,...,-0.261747,0.068364,0.155715,2016-01-21,2016-01-20,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
9,9063_20160117T182712_20160117T183427_T11SMT,0.098329,0.216473,0.031464,0.072852,5943.0,0.053812,33.477901,-117.141998,0.401405,...,-0.299300,0.069213,0.163292,2016-01-21,2016-01-17,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
10,9063_20151231T183752_20151231T183755_T11SMT,0.083996,0.193533,0.023260,0.000228,5943.0,0.039784,33.477901,-117.141998,0.406114,...,-0.366930,0.057544,0.134886,2016-01-21,2015-12-31,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
11,9063_20151228T183312_20151228T183309_T11SMT,0.098287,0.218209,0.035785,0.072584,5943.0,0.053873,33.477901,-117.141998,0.389605,...,-0.298316,0.069005,0.156130,2016-01-21,2015-12-28,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
12,9063_20151218T182802_20151218T182756_T11SMT,0.096120,0.222860,0.021070,0.000702,5943.0,0.044450,33.477901,-117.141998,0.463067,...,-0.381127,0.062066,0.166264,2016-01-21,2015-12-18,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
13,9063_20151208T183312_20151208T183309_T11SMT,0.104930,0.226987,0.026420,0.038293,5943.0,0.051115,33.477901,-117.141998,0.465643,...,-0.353727,0.066359,0.179236,2016-01-21,2015-12-08,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
14,9063_20151121T184422_20151121T184425_T11SMT,0.103866,0.205501,0.024154,0.000007,5943.0,0.048970,33.477901,-117.141998,0.534196,...,-0.374153,0.059208,0.190416,2016-01-21,2015-11-21,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476
15,9063_20151111T184002_20151111T183956_T11SMT,0.095792,0.192474,0.024394,0.012064,5943.0,0.049727,33.477901,-117.141998,0.579812,...,-0.332298,0.052518,0.192658,2016-01-21,2015-11-11,"{""type"":""MultiPoint"",""coordinates"":[]}",71.0,10.0,10.0,5.715476

In [102]:
#export these to csvs
#first dataframe
df_one_final.to_csv('timedf_30_7.csv', index = False)

#second dataframe
df_two_final.to_csv('timedf_70_9.csv', index = False)

#third dataframe
df_three_final.to_csv('timedf_50_8.csv', index = False)